# use container-based infrastructure
sudo: false

env:
  - USE_TRAVIS=true

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,tables,cython,pandas numpy scipy tables cython pandas numexpr matplotlib pyyaml

install:
  - pip install -e .
  - python setup.py build_ext --inplace

script:
  - make test-ci
